# Generated by Django 4.1.4 on 2022-12-14 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extranjería'), ('NIT', 'NIT')], default='CC', max_length=3)),
                ('numero_documento', models.IntegerField(max_length=10, unique=True)),
                ('nombres_apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('numero_telefono', models.IntegerField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, unique=True)),
                ('marca', models.CharField(max_length=20, null=True)),
                ('modelo', models.CharField(max_length=20)),
                ('año', models.IntegerField(max_length=4)),
                ('color', models.CharField(blank=True, max_length=15)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.propietario')),
            ],
        ),
    ]
