# Generated by Django 4.1.4 on 2022-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='numero_documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='numero_telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.IntegerField(),
        ),
    ]
